#!/usr/bin/env bash
shopt -s globstar

rm -rf **/.~lock* **/__pycache__ **/.ipynb_checkpoints
npm run fmt
git checkout solutions
git add --all .
git status
git commit -m "update"
git push
cd ../public
git checkout master
trash *
cp -r ../solutions/* .
rm -r node_modules
trash **/solved* package.json package-lock.json push fmt docs 
git add --all .
git commit -m "update problems"
git push